package com.example.tgbot.entity;

public enum Status {
    REQUEST_NAME,
    REQUEST_PASSWORD,
    AUTHORIZED,
    NOT_AUTHORIZED,
    REQUEST_BOOKMARK,
    REQUEST_TIMETABLE,
    REQUEST_TIMETABLE_TO_DELETE,
    REQUEST_MODULE,
    REQUEST_TIMETABLE_TO_BOOKMARK,
    REQUEST_WEEKDAY,
    REQUEST_TIME,
    REQUEST_STUDENT_NAME,
    IN_CREATING,
    FREE;
}
